Numpy Array Operations

In [87]:
import numpy as np

Indexing And Slicing


In [88]:
#1D Array Indexing And Slicing
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print("Basic Slicing",arr[2:7])
print("With Step",arr[1:8:2])
print("Negative Indexing",arr[-3])

Basic Slicing [3 4 5 6 7]
With Step [2 4 6 8]
Negative Indexing 8


In [89]:
#2D Array Indexing And Slicing
arr_2d=np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
print("Specific element", arr_2d[1,2])
print("Entire row: ",arr_2d[1])
print("Entire row: ",arr_2d[:,1])   #[1,]row    #[,2]col

Specific element 6
Entire row:  [4 5 6]
Entire row:  [2 5 8]


Sorting


In [90]:
unsorted =np.array([3,1,4,1,5,9,2,6])
print("Sorted Array",np.sort(unsorted))

Sorted Array [1 1 2 3 4 5 6 9]


In [91]:
arr_2d_unsorted= np.array([[3,1],
                           [1,2],
                           [2,3]])
print("Sorted 2D Array by column :\n", np.sort(arr_2d_unsorted,axis=0))
print("Sorted 2D Array by row :\n", np.sort(arr_2d_unsorted,axis=1))

Sorted 2D Array by column :
 [[1 1]
 [2 2]
 [3 3]]
Sorted 2D Array by row :
 [[1 3]
 [1 2]
 [2 3]]


Filtering

In [92]:
num = np.array([1,2,3,4,5,6,7,8,9,10])
even_numbers = num[num %2==0]
print("Even Numbers", even_numbers)

Even Numbers [ 2  4  6  8 10]


In [93]:
num = np.array([1,2,3,4,5,6,7,8,9,10])
odd_numbers = num[num % 2==1]
print("Odd Numbers", odd_numbers)

Odd Numbers [1 3 5 7 9]


In [94]:
num = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

even_numbers = num[num % 2 == 0]
odd_numbers = num[num % 2 != 0]

print("Even Numbers:", even_numbers)
print("Odd Numbers:", odd_numbers)


Even Numbers: [ 2  4  6  8 10]
Odd Numbers: [1 3 5 7 9]


Filter With Mask

In [95]:
mask =num > 5
print("Numbers greater than 5 ", num[mask])

Numbers greater than 5  [ 6  7  8  9 10]


In [96]:
mask =num < 5
print("Numbers greater than 5 ", num[mask])

Numbers greater than 5  [1 2 3 4]


Fancy Indexing vs np.where()

In [97]:
num = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])  # Define num first
indices = [0, 2, 4]
print(num[indices])  # Now this works


[1 3 5]


In [98]:
num = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])  # Define num first
where_result = np.where(num > 5)
print(where_result)
print("NP where ", num[where_result])


(array([5, 6, 7, 8, 9]),)
NP where  [ 6  7  8  9 10]


In [99]:
condition_array = np.where(num > 5, num*4, num)
print(condition_array)

[ 1  2  3  4  5 24 28 32 36 40]


In [100]:
condition_array = np.where(num > 5,"true","false")
print(condition_array)

['false' 'false' 'false' 'false' 'false' 'true' 'true' 'true' 'true'
 'true']


Adding And Removing Data

In [101]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
combined = np.concatenate((arr1,arr2))
print(combined)


[1 2 3 4 5 6]


In [102]:
arr = np.array([1,2,3,4,5])
deleted= np.delete(arr,2)
print("Array after deletion:",deleted)


Array after deletion: [1 2 4 5]


Array Compatibility

In [69]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9])

print("Compatibility Shapes ", a.shape == b.shape == c.shape)

Compatibility Shapes  True


In [72]:
a = np.array([1,2,3])
b = np.array([4,5,6,7])
c = np.array([7,8,9])

print("Compatibility Shapes ", a.shape == b.shape == c.shape)

Compatibility Shapes  False


In [76]:
original =np.array([[1,2],[3,4]])
new_row =np.array([[5,6]])

with_new_row = np.vstack((original,new_row))
print(original)
print("\n",with_new_row)

new_col = np.array([[7],[8]])
with_new_col = np.hstack((original,new_col))
print("\n",with_new_col)


[[1 2]
 [3 4]]

 [[1 2]
 [3 4]
 [5 6]]

 [[1 2 7]
 [3 4 8]]
