* What is NumPy?

-> NumPy stands for (Numerical Python) is a Python library that is commonly used for numerical computing.
                   It provides a powerful && dimensional array object, as a well as tools for working with these arrays.

* History:-

-> NumPy was created by Travis Oliphant in 2005,while he was a graduate Student at the Mayo Clinic.

* Installation Method:-

   NumPy Environment Setup:-

  -> pip install numpy .

    How we can use it :-
    
  -> import numpy as np .

* NumPy with other liberaries:-

1. NumPy with Pandas.

2. NumPy with Matplotlib.

3. NumPy with SciPy.



Creating NumPy Arrays


In [6]:
# %pip install numpy

In [3]:
import numpy as np

In [5]:
#creating an array.
# 1D Array.
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [ ]:
#creating 1d and 2d array..
arr_1d=np.array([1,2,3,4,5,6,7,8])
print(arr_1d)

arr_2d=np.array([[1,2,3],[4,5,6]])
print(arr_2d)

[1 2 3 4 5 6 7 8]
[[1 2 3]
 [4 5 6]]


In [34]:
#List vs Numpy array...
import time
start=time.time()
py_list=[i*2 for i in range(1000000)]
print("\n List operation time: ", time.time() - start)

py_list=[1,2,3]
print("Python list multiplication ", py_list * 2)   #list multiplication

np_array=np.array([1,2,3])
print("Python array multiplication ", np_array * 2) #array multiplication       element wise multiplication...




 List operation time:  0.05834031105041504
Python list multiplication  [1, 2, 3, 1, 2, 3]
Python array multiplication  [2 4 6]


In [ ]:
#List vs Numpy...
import time
start=time.time()
py_list=[1,2,3]
py_list=[i*2 for i in range(1000000)]
print("\n List operation time: ", time.time() - start)

start=time.time()
np_array=np.array([1,2,3])
np_array=np.arange(1000000) * 2
print("\n Numpy operation time: ", time.time() - start)






 List operation time:  0.05100131034851074

 Numpy operation time:  0.004003763198852539


In [ ]:
#Creating Array from Scratch.....
zeros=np.zeros([3,4])
print("zeros array:\n ", zeros)  #zeros  array


ones=np.ones([2,3])
print("ones array:\n ", ones)   #ones array 


full = np.full((2,2),9)
print("full : \n ", full)       #full array


random = np.random.random((2, 3))   #random  array
print("random array : \n", random)



sequence = np.arange(0,11,2)        #sequence array 
print("sequence array : \n", sequence)





zeros array:
  [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones array:
  [[1. 1. 1.]
 [1. 1. 1.]]
full : 
  [[9 9]
 [9 9]]
random array : 
 [[0.48161511 0.84119279 0.71656524]
 [0.90609149 0.15476261 0.91632952]]
sequence array : 
 [ 0  2  4  6  8 10]


In [13]:
#creating a 0-D Array.
arrzero=np.array(80)
print(arrzero)

80


In [14]:
#checking the dimension of the array.        .ndim is use to find the dimension of array....
print(arr.ndim)    # 1D
arrzero.ndim       # 2D

1


0

Vector , Matrix and Tensor

In [63]:
vector = np.array([1,2,3])
print("vector:\n ", vector)

matrix = np.array([[1,2,3],[4,5,6]])
print("matrix: \n", matrix)

tensor = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print("tensor: \n", tensor)





vector:
  [1 2 3]
matrix: 
 [[1 2 3]
 [4 5 6]]
tensor: 
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [15]:
# 2D Array.     \\  In 2D  there will be two brackets... //
arr2=np.array([[1,2,3,4,5],[7,8,9,10,11]])
print(arr2)

[[ 1  2  3  4  5]
 [ 7  8  9 10 11]]


Array Properties...

In [72]:
arr=np.array([[1,2,3],
             [4,5,6]])
print("Shape",arr.shape)
print("Dimension",arr.ndim)
print("Size", arr.size)
print("Dtype", arr.dtype)

Shape (2, 3)
Dimension 2
Size 6
Dtype int64


In [16]:
#number of elements...
print(arr.size)
print(arrzero.size)
print(arr2.size)

5
1
10


In [17]:
#Total memory taken by an Array...
print(arr.nbytes)
print(arrzero.nbytes)
print(arr2.nbytes)

40
8
80


In [18]:
#single element size
print(arr.itemsize)
print(arrzero.itemsize)
print(arr2.itemsize)

8
8
8


In [19]:
#for the data type of the array
print(arr.dtype)
print(arrzero.dtype)
arr2.dtype


int64
int64


dtype('int64')

Array Reshaping

In [82]:
arr= np.arange(12)
print("Original Array: ", arr)

reshaped= arr.reshape((3,4))
print("\nReshaped array:\n",reshaped)

flattened = reshaped.flatten()
print("\n Flattened array: \n", flattened)

raveled= reshaped.ravel()      # returns view , instead of copy....
print("\n raveled array: \n", raveled)

transpose= reshaped.T               #transpose
print("\n Transpose array:\n",transpose)   

Original Array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]

Reshaped array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 Flattened array: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]

 raveled array: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Transpose array:
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [20]:
print(arr2)
# [[1,2,3,4,5]     (0th row)
#  7,8,9,10,11]    (1st row row)

[[ 1  2  3  4  5]
 [ 7  8  9 10 11]]


In [21]:
#for the specific element of the Array().
arr2[0,2]

np.int64(3)

In [22]:
#specific row of the Array().
print(arr2[0,:]) 
arr2[1,:]     # colon (:) means saare elements ajayenge...

[1 2 3 4 5]


array([ 7,  8,  9, 10, 11])

In [23]:
arr3 = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr3)

[ 1  2  3  4  5  6  7  8  9 10]


In [24]:
# [Start Index : Ending Index] [inclusive : exclusive]
print(arr3[1:5])    #1st index include     #2nd index exclude....

[2 3 4 5]


In [25]:
print(arr3[5:])     #starting pata h end nhi pata  #inclusive

[ 6  7  8  9 10]


In [26]:
print(arr3[:5])     #ending pata h starting nhi pata  #exclusive

[1 2 3 4 5]


In [27]:
print(arr2)

[[ 1  2  3  4  5]
 [ 7  8  9 10 11]]


In [28]:
print(arr2[1,1:4])

[ 8  9 10]


In [29]:
#copy of an Array...
arr4 = arr2.copy()
print(arr4)

[[ 1  2  3  4  5]
 [ 7  8  9 10 11]]


In [59]:
arr4

array([[ 1,  2,  3,  4,  5],
       [ 7,  8,  9, 10, 11]])

In [ ]:
#Zero matrix...
np.zeros((4,6))       #1st row    #2nd column        (rows,cols)

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [ ]:
#All 1 matrix....  3D Array matrix
np.ones((6,3,3))       #6 Array created     #3 rows   #3cols

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [ ]:
#Other matrix.....
np.full((40,40),645)     #645 no wala matrix created    #40 rows   #40 cols

array([[645, 645, 645, ..., 645, 645, 645],
       [645, 645, 645, ..., 645, 645, 645],
       [645, 645, 645, ..., 645, 645, 645],
       ...,
       [645, 645, 645, ..., 645, 645, 645],
       [645, 645, 645, ..., 645, 645, 645],
       [645, 645, 645, ..., 645, 645, 645]], shape=(40, 40))

In [ ]:
#Other matrix....
np.full((6,4,4),550)  # 6 Array/Matrix created     # 550 no wala matrix created  # 4 rows # 4 cols

array([[[550, 550, 550, 550],
        [550, 550, 550, 550],
        [550, 550, 550, 550],
        [550, 550, 550, 550]],

       [[550, 550, 550, 550],
        [550, 550, 550, 550],
        [550, 550, 550, 550],
        [550, 550, 550, 550]],

       [[550, 550, 550, 550],
        [550, 550, 550, 550],
        [550, 550, 550, 550],
        [550, 550, 550, 550]],

       [[550, 550, 550, 550],
        [550, 550, 550, 550],
        [550, 550, 550, 550],
        [550, 550, 550, 550]],

       [[550, 550, 550, 550],
        [550, 550, 550, 550],
        [550, 550, 550, 550],
        [550, 550, 550, 550]],

       [[550, 550, 550, 550],
        [550, 550, 550, 550],
        [550, 550, 550, 550],
        [550, 550, 550, 550]]])

In [66]:
#Importing random...
from numpy import random

In [ ]:
x= random.randint(100)    #random numbers...
print(x)

91


In [ ]:
#Decimal number matrix... using random numbers...
np.random.rand(4,4)

array([[0.27289152, 0.92163104, 0.5889337 , 0.74161089],
       [0.73492062, 0.3949205 , 0.739593  , 0.22597081],
       [0.64594304, 0.27479232, 0.84150818, 0.24034511],
       [0.85711498, 0.73642166, 0.72537644, 0.47167405]])

In [ ]:
#Identity matrix...
np.identity(6)     #Identity matrix starts with one and ends with one only in cross way \...
      

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [88]:
#Mathematical Operations on matrix/array....
arrm = np.array([10,20,30,40])
print(arrm)


[10 20 30 40]


In [95]:
#Addition operation...
arrm= arrm+15
print(arrm)


[25 35 45 55]


In [ ]:
#Subtraction Operation...
arrm= arrm-40
print(arrm)


[-15  -5   5  15]


In [100]:
arrz=arrm+100
arrz

array([ 85,  95, 105, 115])

In [104]:
#Multiplication Operation...
print(arrz)
arrz*10

[ 85  95 105 115]


array([ 850,  950, 1050, 1150])

In [107]:
#Division Operation...
print(arrz)
arrz/5

[ 85  95 105 115]


array([17., 19., 21., 23.])

In [ ]:
#Addition of Two different matrix/arrays...
a1 =np.array([1,2,3,4,5])
a2 =np.array([10,15,20,25,30])
print(a1+a2)

[11 17 23 29 35]


In [ ]:
#Subtraction of Two different matrix/arrays...
a1 =np.array([1,2,3,4,5])
a2 =np.array([10,15,20,25,30])
print(a1-a2)

[ -9 -13 -17 -21 -25]


In [110]:
#Multiplication of Two different matrix/arrays...
a1 =np.array([1,2,3,4,5])
a2 =np.array([10,15,20,25,30])
print(a1*a2)

[ 10  30  60 100 150]


In [ ]:
#Division of Two different matrix/arrays...
a1 =np.array([1,2,3,4,5])
a2 =np.array([10,15,20,25,30])
print(a2/a1)

[10.          7.5         6.66666667  6.25        6.        ]


In [114]:
# Cos function in an Array/Matrix....
np.cos(a1)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219])

In [115]:
print(arr2)

[[ 1  2  3  4  5]
 [ 7  8  9 10 11]]


In [ ]:
#Creating Minimum And Maximum Value....
print(np.min(arr2))    #minimum value
print(np.max(arr2))    #maximum value

1
11


In [129]:
#Finding the Sum of an Array...
np.sum(arr2)     #Total Sum of matrix = 60

np.int64(60)

In [ ]:
#Iterating in 1D Array...
for x in a1:
    print(x)

1
2
3
4
5


In [140]:
#Iterating in 2D Array...
for z in arr2:
    print(z)

[1 2 3 4 5]
[ 7  8  9 10 11]


In [ ]:
#Iterating in 2D Array...
for a in arr2:
    for b in a:
        print(b)

1
2
3
4
5
7
8
9
10
11
